# Site settings
title: fatina's Blog  # Your Title
tagline:  'Learn more things will make me happy'  # A brief tagline for your site
sidebar_image: /images/touxiang.jpg
timezone: 'Asia/beijing'
destination: ./_site


# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
codeurl: /code/
abouturl: /about/
fragmenturl: /fragment/
permalink: /code/:title

#page
paginate: 7
paginate_path: "code/page:num"
gems: [jekyll-paginate]

highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
incremental: false

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true
 # input: GFM
  extensions:
    - autolink
    - footnotes
    - smart

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style